[package]
name = "mp4-inspect"
version = "0.1.0"
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
repository.workspace = true
license.workspace = true

[features]
default = ["std"]
std = ["alloc"]
alloc = ["mp4-bmff/alloc"]

[dependencies]
mp4-bmff = { workspace = true, default-features = false }

[lints]
workspace = true
