[workspace]
resolver = "2"
members = [
    "crates/mp4-bmff",
]

[workspace.package]
authors = ["Ryohei Kato <r-kato@musen.co.jp>"]
repository = "https://github.com/Kato-emb/mp4-bmff-rs"
license = "MIT OR Apache-2.0"

[workspace.dependencies]
clap = { version = "4", default-features = false, features = ["std", "derive"] }

