[package]
name = "mp4-bmff"
version = "0.1.0"
edition = "2024"
rust-version = "1.87"
repository = "https://github.com/Kato-emb/mp4-bmff-rs"

[features]
default = ["std", "avc", "mp4"]

alloc = []
std = ["alloc"]

avc = []
mp4 = []

[dependencies]

[dev-dependencies]
clap = { version = "4", default-features = false, features = ["std", "derive"] }
criterion = { version = "0.8", features = ["html_reports"] }

[[bench]]
name = "codec"
harness = false

[[example]]
name = "dump"
path = "./examples/dump.rs"

[[example]]
name = "remux"
path = "./examples/remux.rs"
