[package]
name = "mp4-bmff-util"
version = "0.1.0"
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
repository.workspace = true
license.workspace = true

[features]
default = ["std", "io"]

std = ["alloc", "mp4-bmff/std"]
alloc = ["mp4-bmff/alloc"]

io = ["std"]

[dependencies]
mp4-bmff = { workspace = true, default-features = false }

[lints]
workspace = true
