[package]
name = "mp4-bmff"
version = "0.1.0"
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
description = "A pure Rust, zero-copy implementation of ISO Base Media File Format (ISOBMFF/MP4)"
readme = "README.md"
repository.workspace = true
license.workspace = true
keywords = ["no_std", "isobmff", "mp4", "parser", "multimedia"]
categories = ["data-structures", "no-std"]

[package.metadata.docs.rs]
all-features = true

[features]
default = ["alloc", "avc", "mp4"]

alloc = []

# ISO/IEC 14496-1
systems = []

# ISO/IEC 14496-14
mp4 = ["systems"]

# ISO/IEC 14496-15
avc = ["systems"]
hevc = ["systems"]

[dependencies]

[dev-dependencies]

[lints]
workspace = true
